# Generated by Django 5.2.4 on 2025-07-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0054_delete_notyetregisteredgenericsetting_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="simplepage",
            name="hidden_field_for_test",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
